### ISSUE TITLE
 FAILURE: Build failed with an exception. 

### ISSUE THREAD

**Issue by Zeeshan0201** [fluttercommunity/flutter_downloader#91] opened 2019-07-30 09:35 UTC
* What went wrong: Execution failed for task ':app:transformClassesWithMultidexlistForDebug'. > com.android.build.api.transform.TransformException: Error while generating the main dex list:   Error while merging dex archives:    Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.   Program type already present: androidx.work.ArrayCreatingInputMerger  * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.  * Get more help at https://help.gradle.org  BUILD FAILED in 3s ******************************************************************************************* The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app. See https://goo.gl/CP92wY for more information on the problem and how to fix it. ******************************************************************************************* Gradle task assembleDebug failed with exit code 1
Getting this build error after using flutter_downloader package...

**Comment by hnvn** [comment] 2019-07-30 14:01
Have you configured your Android project with AndroidX yet?

**Comment by Zeeshan0201** [comment] 2019-07-30 16:02
Yes,i already upgraded my project in AndroidX...
Here is more details..
https://stackoverflow.com/questions/57270298/program-type-already-present-androidx-work-arraycreatinginputmerger

**Comment by Zeeshan0201** [comment] 2019-07-31 09:34
@hnvn can you please check and reply as soon as possible?

**Comment by hnvn** [comment] 2019-07-31 14:26
What about this one: https://github.com/flutter/flutter/issues/20760

**Comment by Zeeshan0201** [comment] 2019-08-01 05:42
@hnvn tried all solutions, none of those worked for me ! same error coming after flutter clean and flutter create . after deleting android folder..

**Comment by Zeeshan0201** [comment] 2019-08-01 05:54
@hnvn and it's just coming  after getting package  

> flutter_downloader: ^1.1.9

 in **pubcpec.yaml** aftr removing package error also gone everytime...

**Comment by Zeeshan0201** [comment] 2019-08-01 05:55
![Screenshot from 2019-08-01 11-25-49](https://user-images.githubusercontent.com/45591301/62268937-1fc60d00-b44f-11e9-8ac5-b88e225d5a18.png)

**Comment by hnvn** [comment] 2019-08-01 13:30
It'd better to have a project that I can reproduce this issue

**Comment by KyawNaingTun** [comment] 2019-08-05 08:51
Same error
![Screen Shot 2019-08-05 at 3 20 37 PM](https://user-images.githubusercontent.com/6079250/62451639-a43cc680-b794-11e9-8027-adf152bfd30c.png)

**Comment by AmmarHazem** [comment] 2019-08-15 19:55
same problem after installing the package and modifying the AndroidManifest.xml
can you tell me the path of the AndroidManifest file that I should add the provider to ?
![Capture](https://user-images.githubusercontent.com/30551135/63122572-5f403d80-bfa7-11e9-83ac-5a1682885286.PNG)

**Comment by Mahfoud047** [comment] 2019-08-23 19:09
@hnvn, Is there any news, I am getting the same issue with flutter_downloader v1.1.9

**Comment by Zeeshan0201** [comment] 2019-08-24 06:59
@hnvn now it's going serious issue for this package please try to resolve if possible, if needed i will share demo project for reproduction of it!

**Comment by hnvn** [comment] 2019-08-24 08:12
>It'd better to have a project that I can reproduce this issue

**Comment by terryBaz** [comment] 2019-08-24 17:56
same error here 
```
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "project\android\gradlew.bat" exited abnormally: 

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Configure project :flutter_downloader
         *********************************************************
WARNING: This version of connectivity will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_downloader'.
> Could not resolve all artifacts for configuration ':flutter_downloader:classpath'.
   > Could not download builder.jar (com.android.tools.build:builder:3.4.2)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.4.2/builder-3.4.2.jar'.
         > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11m 14s
  Command: project\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.
```

**Comment by terryBaz** [comment] 2019-08-24 17:58
@hnvn you do not need a specific project setup, just use `flutter_downloader: ^1.1.9` good luck

**Comment by hnvn** [comment] 2019-08-25 03:50
What do you mean? Can you run `example` project?

**Comment by Zeeshan0201** [comment] 2019-08-25 03:56
@hvnv  i also got this issue in example project too... might be there was a gradle issue.you can check in example project....will share gradle versioning details..

**Comment by hnvn** [comment] 2019-08-25 08:09
I can say for sure that the example project working well. I am still working on it. It may come from your Gradle version or setting. Try to debug with Gradle commands

**Comment by terryBaz** [comment] 2019-08-25 14:19
you are right @hnvn the code example is working well _(except an a small error which @Zeeshan0201 encounter and it does not have relation with the current issue, I made a PR to fix it https://github.com/fluttercommunity/flutter_downloader/pull/108)_ I will dig in to see what I could do with this current issue.

**Comment by hnvn** [comment] 2019-08-26 03:13
As far as I understand this issue, you need to correct your Gradle setting, it may look like:

`build.gradle`:
```
   dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
    }
```

`gradle-wrapper.properties`:
```
   distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
```

**Comment by terryBaz** [comment] 2019-08-26 06:17
> As far as I understand this issue, you need to correct your Gradle setting, it may look like:
> 
> `build.gradle`:
> 
> ```
>    dependencies {
>         classpath 'com.android.tools.build:gradle:3.4.2'
>     }
> ```
> 
> `gradle-wrapper.properties`:
> 
> ```
>    distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
> ```

I tried this before and it did not work for me.

**Comment by terryBaz** [comment] 2019-08-26 06:29
great news, I found a solution : 

` android/build.gradle` :
```groovy
buildscript {
   //...
    dependencies {
      //...        
     classpath 'com.android.tools.build:gradle:3.3.2'
    }
}
```

```groovy
subprojects {
    //...

    project.configurations.all {

        exclude group: 'com.google.guava', module: 'failureaccess'


        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "26.1.0"
            }

            if('guava' == details.requested.name) {
                details.useVersion '27.0-android'
            }

        }
    }
}
```

`android/gradle/wrapper/gradle-wrapper.properties` :
```groovy
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.3-all.zip
```

@Zeeshan0201 please confirm if it is woking for you (and close the issue)

**Comment by Zeeshan0201** [comment] 2019-08-26 06:53
@terryBaz okay, will check and reply :+1:

**Comment by Mahfoud047** [comment] 2019-08-26 07:31
@terryBaz, Thanks It works for me.

**Closed** 2019-08-26 10:03 UTC
