### ISSUE TITLE
Not Saving file in desired given path

### ISSUE THREAD

**Issue by krunal1156** [fluttercommunity/flutter_downloader#540] opened 2021-09-29 06:58 UTC
I have updated the library from 1.6.1 to 1.7.0 
i am facing very strange issue in android only in ios library works fine..
in android  i m not able to store file in given desire location by default library store files in  download folder only. i have checked the libraries database where its manages taskId and path and urls. in that database given storage path is what i set while download the request but file not saved on that location and instead of that location its stores files only in the download folder of external storage only.

**Comment by mpeng5120** [comment] 2021-09-30 02:03
一样在Bug ,传了保存路径没有用到，  DownloadWorker.java   341行   saveFilePath

**Comment by yelkamel** [comment] 2021-10-01 08:48
I have the same issue :/

**Comment by hnvn** [comment] 2021-10-09 03:42
Duplicate of #533. Please have a look at this [comment](https://github.com/fluttercommunity/flutter_downloader/issues/533#issuecomment-939214932).

**Closed by hnvn** 2021-10-09 03:42 UTC
