### ISSUE TITLE
java.lang.NullPointerException: uri

### ISSUE THREAD

**Issue by thephenomenal10** [fluttercommunity/flutter_downloader#537] opened 2021-09-22 15:54 UTC
Unable to download the file.
this error occurs when I am running the app on the Android 10 version, it works fine with Android 11.

W/System.err(32119): java.lang.NullPointerException: uri
W/System.err(32119): 	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:133)
W/System.err(32119): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1490)
W/System.err(32119): 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1240)
W/System.err(32119): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:358)
W/System.err(32119): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:208)
W/System.err(32119): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err(32119): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(32119): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(32119): 	at java.lang.Thread.run(Thread.java:919)
I/WM-WorkerWrapper(32119): Worker result FAILURE for Work [ id=99ed630a-5a93-4ec8-8fd6-56c04e36b710, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]

**Comment by bugrevealingbme** [comment] 2021-10-02 15:01
Same as

**Comment by hnvn** [comment] 2021-10-09 03:32
Duplicate of #548

**Closed by hnvn** 2021-10-09 03:32 UTC
