### ISSUE TITLE
Crash app

### ISSUE THREAD

**Issue by vanvixi** [fluttercommunity/flutter_downloader#849] opened 2023-04-19 14:23 UTC
**Describe the bug**
Crash app

**Devices:** emulator (API 29 - 30)

**Flutter version:** v3.3.2

**Lib:** 
```
  flutter_downloader: ^1.10.2
  permission_handler: ^10.2.0
```
 **Log:**
```
Launching lib/main.dart on Android SDK built for arm64 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Debug service listening on ws://127.0.0.1:58798/hv9vq9Tr8rE=/ws
Syncing files to device Android SDK built for arm64...
D/EGL_emulation( 6470): eglMakeCurrent: 0x7a9e0c06c0: ver 3 0 (tinfo 0x7b33a2c680)
D/EGL_emulation( 6470): eglCreateContext: 0x7a48c114a0: maj 3 min 0 rcv 3
D/EGL_emulation( 6470): eglCreateContext: 0x7a48c11540: maj 3 min 0 rcv 3
D/HostConnection( 6470): HostConnection::get() New Host Connection established 0x7a48c130c0, tid 6551
D/HostConnection( 6470): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation( 6470): eglMakeCurrent: 0x7a48c11540: ver 3 0 (tinfo 0x7a9e536d40)
D/DownloadWorker( 6470): DownloadWorker{url=https://www.kozco.com/tech/LRMonoPhase4.mp3,filename=LRMonoPhase4.mp3,savedDir=/storage/emulated/0/Download,header={},isResume=false,status=ENQUEUED
D/DownloadWorker( 6470): Update notification: {notificationId: 1, title: LRMonoPhase4.mp3, status: RUNNING, progress: 0}
D/DownloadWorker( 6470): Open connection to https://www.kozco.com/tech/LRMonoPhase4.mp3
D/DownloadWorker( 6470): Headers = {}
I/trustAllHosts( 6470): checkServerTrusted
I/flutter ( 6470): fatal error: could not find callback
D/HostConnection( 6470): HostConnection::get() New Host Connection established 0x7a9e0181c0, tid 6549
D/HostConnection( 6470): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
Lost connection to device.
```
**My Code**
```
import 'package:flutter/material.dart';
import 'package:flutter_downloader/flutter_downloader.dart';
import 'package:permission_handler/permission_handler.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Plugin must be initialized before using
  await FlutterDownloader.initialize(
      debug: true,
      // optional: set to false to disable printing logs to console (default: true)
      ignoreSsl:
          true // option: set to false to disable working with http links (default: false)
      );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter Download'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: _download,
          child: const Text('Download'),
        ),
      ),
    );
  }

  void _download() async {
    final status = await Permission.storage.request();

    if (status.isGranted) {
      final id = await FlutterDownloader.enqueue(
        fileName: "LRMonoPhase4.mp3",
        url: 'https://www.kozco.com/tech/LRMonoPhase4.mp3',
        savedDir: '/storage/emulated/0/Download',
        showNotification: true,
        openFileFromNotification: true,
      );
    } else {
      print('Permission Denied');
    }
  }
}
```
**AndroidManifest.xml**

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.flutter_download_file">
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        tools:ignore="ScopedStorage" />
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>
   <application
        android:label="flutter_download_file"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
       android:usesCleartextTraffic="true"
       tools:targetApi="m">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
       <provider
           android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
           android:authorities="${applicationId}.flutter_downloader.provider"
           android:exported="false"
           android:grantUriPermissions="true">
           <meta-data
               android:name="android.support.FILE_PROVIDER_PATHS"
               android:resource="@xml/provider_paths"/>
       </provider>
       <!-- Begin FlutterDownloader customization -->
       <!-- disable default Initializer -->
       <provider
           android:name="androidx.startup.InitializationProvider"
           android:authorities="${applicationId}.androidx-startup"
           android:exported="false"
           tools:node="merge">
           <meta-data
               android:name="androidx.work.WorkManagerInitializer"
               android:value="androidx.startup"
               tools:node="remove" />
       </provider>

       <!-- declare customized Initializer -->
       <provider
           android:name="vn.hunghd.flutterdownloader.FlutterDownloaderInitializer"
           android:authorities="${applicationId}.flutter-downloader-init"
           android:exported="false">
           <!-- changes this number to configure the maximum number of concurrent tasks -->
           <meta-data
               android:name="vn.hunghd.flutterdownloader.MAX_CONCURRENT_TASKS"
               android:value="5" />
       </provider>
       <!-- End FlutterDownloader customization -->
    </application>
</manifest>

```

**Comment by TimestampWombat** [comment] 2023-04-19 15:56
The code `I/flutter ( 6470): fatal error: could not find callback` tells where the problem is. 
You never call `FlutterDownloader.registerCallback`.
Check the example.

**Comment by vanvi9x** [comment] 2023-04-20 05:02
> The code `I/flutter ( 6470): fatal error: could not find callback` tells where the problem is. You never call `FlutterDownloader.registerCallback`. Check the example.

I need to call `FlutterDownloader.registerCallback` even if I don't need it?

**Comment by bartekpacia** [comment] 2023-04-23 08:45
You, you have to.

If you'd like to spare some time to future users of this package, please submit a PR updating the README B)

**Comment by bartekpacia** [comment] 2023-08-04 11:02
Duplicate of #445

**Closed by bartekpacia** 2023-08-04 11:02 UTC
Labels: bug
