### ISSUE TITLE
open apk file by iQiyi and throw an error

### ISSUE THREAD

**Issue by zoujinbin** [fluttercommunity/flutter_downloader#78] opened 2019-06-20 03:32 UTC
I had downloaded the apk file via flutter_downloader plugin, and once i open the apk file, it opend the iQiyi and throw an error.The following is my code:
```
// 发起请求
    final taskId = await FlutterDownloader.enqueue(
        url: url,
        fileName: 'rcb.apk',
        savedDir: localPath.path,
        showNotification: false,
        openFileFromNotification: false);

    FlutterDownloader.registerCallback((id, status, progress) {
      // 更新下载进度
      setState(() => this.progress = progress);
      // 当下载完成时，调用安装
      if (taskId == id && status == DownloadTaskStatus.complete) {
        // 关闭更新进度框
        Navigator.of(context).pop();
        FlutterDownloader.open(taskId: taskId);
      }
    });
    return taskId;
```

Flutter info
```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.472], locale zh-CN)
    • Flutter version 1.5.4-hotfix.2 at D:\software\flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\software\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\software\Android\Sdk
    • Java binary at: D:\software\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Android Studio (version 3.2)
    • Android Studio at D:\software\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • SM G9500 • 98895a45473444434f • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

**Comment by bartekpacia** [comment] 2022-05-23 10:48
Closing because this is old and isn't reproducible.

**Closed by bartekpacia** 2022-05-23 10:48 UTC
