### ISSUE TITLE
Fatal: failed to find callback

### ISSUE THREAD

**Issue by chainzhang** [fluttercommunity/flutter_downloader#140] opened 2019-10-17 11:39 UTC
Recently I upgraded this plugin and got this error:
```
E/DownloadWorker( 7363): Fatal: failed to find callback
```

I had followed the instruction to set up the codes on Android and iOS, on Flutter side I used a wrapper and the implementation like: 

```
...
static void downloadCallback(String id, DownloadTaskStatus status, int progress) {
    if (taskFuncMap.containsKey(id)) {
      if (status == DownloadTaskStatus.complete) {
        taskFuncMap[id](STATUS_COMPLETE);
      } else if (status == DownloadTaskStatus.failed) {
        taskDirMap[id].delete(recursive: true);
        taskFuncMap[id](STATUS_FAILED);
      }
    }
  }

  Downloader._internal() {
    FlutterDownloader.registerCallback(downloadCallback);
  }
```
Could someone give me some hints to figure out this issue?
Thank you!

**Comment by mrdong916** [comment] 2019-10-17 12:00
have same problem

**Comment by hnvn** [comment] 2019-10-17 13:06
Does it happen in the example project?

**Comment by mrdong916** [comment] 2019-10-17 13:08
是的 就是照着实例写的

**Comment by hnvn** [comment] 2019-10-17 13:21
I mean the example project in this repository. Can you give me a project to reproduce this issue?

**Comment by mrdong916** [comment] 2019-10-17 13:49
Sorry, my English is very bad, all rely on translation software, here is the code I generated this problem.

```
static Future<String> download(
      String url, String downloadPath, String fileName) async {
    ToastUtil.show(KStrings.startDownload);
    return await FlutterDownloader.enqueue(
      url: url,
      savedDir: downloadPath,
      fileName: fileName,
      headers: {
        'token': ""
      },
      showNotification: true
      openFileFromNotification: true, 
    );
  }
```


```
@override
  void initState() {
    super.initState();
    _controller.addListener(() {
      if (_controller.position.pixels == _controller.position.maxScrollExtent) {
        setState(() {
          this._page++;
        });
        print("页数：${this._page}");
        loadData();
      }
    });

    // 加载数据
    loadData();
    // 监听下载任务

    // 注册端口
    IsolateNameServer.registerPortWithName(
        _port.sendPort, 'downloader_send_port');
    // 端口监听
    _port.listen((dynamic data) {
      // 获取数据
      String id = data[0];
      DownloadTaskStatus status = data[1];
      int progress = data[2];
      // 判断状态
      if (status.value <= 1) {
        loadData();
      }

      int index = _dms.indexWhere((dm) => dm.taskId == id);
      DownloadModel dm = _dms[index];
      dm.progress = progress;
      dm.status = status.value;
      setState(() {
        _dms[index] = dm;
      });
    });

    // 注册回调监听
    FlutterDownloader.registerCallback(downloadCallback);
  }
```

**Comment by hnvn** [comment] 2019-10-17 13:54
Not much useful, please try to create a GitHub project that I can run and reproduce the issue with it because I am sure that the example project in this repository working well

**Comment by mrdong916** [comment] 2019-10-18 01:50
This is the demo with the error, the following is the error message of the demo.

https://github.com/mrdong916/flutter-app-demo

```
Performing hot restart...
Syncing files to device MI 8 UD...
Restarted application in 1,962ms.
W/WM-WorkSpec(30509): Backoff delay duration less than minimum value
I/flutter (30509): Download task is enqueued with id(4eb8ccac-a25e-4603-8a65-6ceba4c928bb)
E/DownloadWorker(30509): Fatal: failed to find callback
D/DownloadWorker(30509): DownloadWorker{url=https://dldir1.qq.com/qqyy/pc/tuiguang/QQPlayerForYQQ_39_923.exe,filename=fineName.exe,savedDir=/storage/emulated/0/,header=,isResume=false
D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
D/DownloadWorker(30509): Open connection to https://dldir1.qq.com/qqyy/pc/tuiguang/QQPlayerForYQQ_39_923.exe
D/DownloadWorker(30509): Content-Type = application/octet-stream
D/DownloadWorker(30509): Content-Length = 27738144
D/DownloadWorker(30509): Charset = null
D/DownloadWorker(30509): fileName = fineName.exe
D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
D/DownloadWorker(30509): Setting an intent to open the file /storage/emulated/0//fineName.exe
D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
D/DownloadWorker(30509): File downloaded
I/WM-WorkerWrapper(30509): Worker result SUCCESS for Work [ id=4eb8ccac-a25e-4603-8a65-6ceba4c928bb, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]

```

**Comment by alanmlira** [comment] 2019-10-18 04:22
I'm receiving this same problem:
```
I/flutter (27378): Download task is enqueued with id(7c2cb95b-4f71-431b-9248-d3f752516f4c)
I/flutter (27378): downloadFile.taskId: 7c2cb95b-4f71-431b-9248-d3f752516f4c
E/DownloadWorker(27378): Fatal: failed to find callback
D/skia    (27378): --- SkAndroidCodec::NewFromStream returned null
D/skia    (27378): --- SkAndroidCodec::NewFromStream returned null
D/skia    (27378): --- SkAndroidCodec::NewFromStream returned null
```
PS: Testing on the example project in this repository works.

**Comment by chainzhang** [comment] 2019-10-18 06:20
@hnvn Sorry, I found that I forgot calling `FlutterDownloader.initialize()` before running the App instance.
I didn't know that it's required. It would be nice to indicate this usage in the document.
Anyway, thanks for making this awesome plugin.

```
await FlutterDownloader.initialize();
runApp(App());
```

@alanmlira @mrdong916 I Hope it helps.

**Comment by hnvn** [comment] 2019-10-18 06:29
Yep, it's required. I also forget documenting for it.

**Comment by alanmlira** [comment] 2019-10-18 13:32
@chainzhang that's it, now it's working. 

Thank you all.

**Comment by hnvn** [comment] 2019-10-18 23:32
I believe this issue is fixed by @chainzhang 's comment or you can checkout v1.3.1 to ensure the plugin initialized correctly.

**Closed by hnvn** 2019-10-18 23:32 UTC

**Comment by vishwajit76** [comment] 2020-10-11 12:04
> This is the demo with the error, the following is the error message of the demo.
> 
> https://github.com/mrdong916/flutter-app-demo
> 
> ```
> Performing hot restart...
> Syncing files to device MI 8 UD...
> Restarted application in 1,962ms.
> W/WM-WorkSpec(30509): Backoff delay duration less than minimum value
> I/flutter (30509): Download task is enqueued with id(4eb8ccac-a25e-4603-8a65-6ceba4c928bb)
> E/DownloadWorker(30509): Fatal: failed to find callback
> D/DownloadWorker(30509): DownloadWorker{url=https://dldir1.qq.com/qqyy/pc/tuiguang/QQPlayerForYQQ_39_923.exe,filename=fineName.exe,savedDir=/storage/emulated/0/,header=,isResume=false
> D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
> D/DownloadWorker(30509): Open connection to https://dldir1.qq.com/qqyy/pc/tuiguang/QQPlayerForYQQ_39_923.exe
> D/DownloadWorker(30509): Content-Type = application/octet-stream
> D/DownloadWorker(30509): Content-Length = 27738144
> D/DownloadWorker(30509): Charset = null
> D/DownloadWorker(30509): fileName = fineName.exe
> D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
> D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
> D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
> D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
> D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
> D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
> D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
> D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
> D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
> D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
> D/DownloadWorker(30509): Setting an intent to open the file /storage/emulated/0//fineName.exe
> D/skia    (30509): --- Failed to create image decoder with message 'unimplemented'
> D/DownloadWorker(30509): File downloaded
> I/WM-WorkerWrapper(30509): Worker result SUCCESS for Work [ id=4eb8ccac-a25e-4603-8a65-6ceba4c928bb, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
> ```

I have the same problem on flutter v1.22 or later.

**Comment by vishwajit76** [comment] 2020-10-11 12:05
I/WM-WorkerWrapper(12967): Worker result SUCCESS for Work [ id=de476107-d05a-4b5d-a96d-fa8cb78636b7, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
