### ISSUE TITLE
Not work in iOS 15

### ISSUE THREAD

**Issue by FernandoGonz** [fluttercommunity/flutter_downloader#570] opened 2021-11-26 23:29 UTC
Not work in iOS 15 with 1.7.1 library version

2021-11-26 16:00:24.439393-0600 Runner[2524:891181] open DB successfully
2021-11-26 16:00:24.440492-0600 Runner[2524:891181] Query was executed successfully. Affected rows = 1
2021-11-26 16:00:24.440572-0600 Runner[2524:891181] URLSession:task:didCompleteWithError:
2021-11-26 16:00:24.440597-0600 Runner[2524:891181] HTTP status code: 200

**Comment by aravind-b-dev** [comment] 2021-12-01 10:24
use this for download directory    

    directory = await getExternalStorageDirectory();

**Comment by rkoshti** [comment] 2022-01-13 11:47
@FernandoGonz Did you found any work around for this? I am facing the same error in iOS 15.2

**Comment by d9media** [comment] 2022-01-19 03:42
This may be helpful: https://stackoverflow.com/questions/59501445/flutter-how-to-save-a-file-on-ios?noredirect=1&lq=1

**Comment by bartekpacia** [comment] 2022-05-23 10:41
duplicate of #569

**Closed by bartekpacia** 2022-05-23 10:41 UTC
