### ISSUE TITLE
Notifications on iOS don't show up (the permission is granted)

### ISSUE THREAD

**Issue by iamtusar** [fluttercommunity/flutter_downloader#832] opened 2023-03-10 09:11 UTC
I am not able to track this issue, please let me know how should I handle this thing. I am trying for the last few hours. 
even I am not getting any updates in debug mode as well, and I have already provided notification permission. 
![Screenshot 2023-03-10 at 14 48 08](https://user-images.githubusercontent.com/67088685/224275847-e8c17604-5311-4d92-9896-d8a381649b92.png)

  Directory? appDocDir = Platform.isAndroid
      ? await getExternalStorageDirectory()
      : await getApplicationDocumentsDirectory();

  String pathToSave = Platform.isAndroid
      ? '${appDocDir!.path.split('/Android/')[0]}/Download/'
      : appDocDir!.path;

  String? taskId = (await FlutterDownloader.enqueue(
    url: fileUrl,
    savedDir: pathToSave,
    showNotification: true,
    openFileFromNotification: true,
    fileName: "$finalString _$getLastStoredValue.pdf",

    // saveInPublicStorage: true,
  ));
  
  apart from that I have setup all things for iOS as described in the library, but still facing issues. 
 I am using 11 pro max with iOS 16.2 simulator. 
 @bartekpacia

**Comment by bartekpacia** [comment] 2023-03-12 15:40
Sorry but I can't help you without a minimal, reproducible sample.

**Comment by iamtusar** [comment] 2023-03-12 16:12
> Sorry but I can't help you without a minimal, reproducible sample.



> Sorry but I can't help you without a minimal, reproducible sample.

I have updated my comment, please check it.

**Comment by bartekpacia** [comment] 2023-03-12 16:17
You have to manually request iOS permission (using some other plugin, e.g. [permission_handler](https://pub.dev/packages/permission_handler)).

Unfortunately, this library doesn't do it for you.

This bug is tracked as #710.

**Comment by iamtusar** [comment] 2023-03-12 16:23
> You have to manually request iOS permission (using some other plugin, e.g. [permission_handler](https://pub.dev/packages/permission_handler)).
> 
> Unfortunately, this library doesn't do it for you.
> 
> This bug is tracked as #710.

I am already using permission_handler for notification permission, and after accepting the notification permission, it still does not work for me.

**Comment by bartekpacia** [comment] 2023-03-12 16:27
Well... then it's a bug. I don't have time to fix it, but if you're willing to submit a PR, I'll be happy to review it.

**Comment by 781flyingdutchman** [comment] 2023-03-25 07:03
Try [background_downloader](https://pub.dev/packages/background_downloader) - an alternative that supports notifications on iOS and Android

**Comment by salmaahhmed** [comment] 2023-10-24 09:03
duplicate of #710

**Closed by salmaahhmed** 2023-10-24 09:03 UTC
Labels: bug
