### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by cl136787252** [fluttercommunity/flutter_downloader#542] opened 2021-09-30 08:47 UTC
Unable to download the file.
this error occurs when I am running the app on the Android 9 version, 
flutter_downloader：1.7.0

W/WM-WorkSpec(26435): Backoff delay duration less than minimum value
D/DownloadWorker(26435): DownloadWorker{url=https://orderfile.zysaz.com/order/20210930/EgcbmjpQnpV.dwg,filename=F_c7e78cea63e547a6b2eabaa55a8feaf2.dwg,savedDir=/storage/emulated/0/Android/data/com.lil.yjj.ntv/files/Download,header={"auth": "test_for_sql_encoding"},isResume=false
D/DownloadWorker(26435): Open connection to https://orderfile.zysaz.com/order/20210930/EgcbmjpQnpV.dwg
D/DownloadWorker(26435): Headers = {"auth": "test_for_sql_encoding"}
D/CrashReport(26435): checkServerTrusted
D/DownloadWorker(26435): Content-Type = application/octet-stream
D/DownloadWorker(26435): Content-Length = 2810368
D/DownloadWorker(26435): Charset = null
D/DownloadWorker(26435): fileName = F_c7e78cea63e547a6b2eabaa55a8feaf2.dwg
W/System.err(26435): java.lang.NullPointerException
W/System.err(26435): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
W/System.err(26435): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:362)
W/System.err(26435): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:208)
W/System.err(26435): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err(26435): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(26435): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(26435): 	at java.lang.Thread.run(Thread.java:764)
I/WM-WorkerWrapper(26435): Worker result FAILURE for Work [ id=6aa295aa-a05b-472a-ac4c-da430d33b371, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]

**Comment by sanalkv** [comment] 2021-09-30 09:15
Make sure that you are requesting permission. Please check the example project on how you can do it.

**Comment by bugrevealingbme** [comment] 2021-10-02 14:34
Same as.

**Comment by hnvn** [comment] 2021-10-09 03:33
Duplicate of #548

**Closed by hnvn** 2021-10-09 03:33 UTC
