### ISSUE TITLE
The Application must be implemented PluginRegistrantCallback

### ISSUE THREAD

**Issue by panjt1995** [fluttercommunity/flutter_downloader#166] opened 2019-11-08 21:14 UTC
I have copied the example project, give me the following error. Instead when I used version 1.2.0 everything were ok.
`W/WM-WorkSpec( 3254): Backoff delay duration less than minimum value
I/flutter ( 3254): Download task is enqueued with id(1c2c9c23-8fee-4495-8726-5b8088e51bec)
D/AndroidRuntime( 3254): Shutting down VM
E/AndroidRuntime( 3254): FATAL EXCEPTION: main
E/AndroidRuntime( 3254): Process: com.example.pj, PID: 3254
E/AndroidRuntime( 3254): java.lang.AssertionError: The Application must be implemented PluginRegistrantCallback
E/AndroidRuntime( 3254):        at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:106)
E/AndroidRuntime( 3254):        at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
E/AndroidRuntime( 3254):        at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
E/AndroidRuntime( 3254):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 3254):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3254):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 3254):        at android.app.ActivityThread.main(ActivityThread.java:6680)
E/AndroidRuntime( 3254):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3254):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 3254):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process ( 3254): Sending signal. PID: 3254 SIG: 9`

**Comment by hnvn** [comment] 2019-11-09 00:43
Duplicate of #141, #152 
Btw, if you read the integration document carefully, you would avoid this exception. Thanks for your feedback.

**Closed by hnvn** 2019-11-09 00:43 UTC
