### ISSUE TITLE
Objective-C warnings during app compilation

### ISSUE THREAD

**Issue by Matej-Hlatky** [fluttercommunity/flutter_downloader#424] opened 2021-03-16 08:56 UTC
Hello,
when building Flutter iOS app (`flutter build ios`) with latest `flutter_downloader` version 1.5.2 as a dependency, we got these warnings:

```
/ios/Classes/FlutterDownloaderPlugin.m:169:103: values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead [-Wformat]
     return [NSString stringWithFormat: @"%@.%lu", [[[self currentSession] configuration] identifier], [task taskIdentifier]];

/ios/Classes/FlutterDownloaderPlugin.m:174:89: values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead [-Wformat]
     return [NSString stringWithFormat: @"%@.%lu", [[session configuration] identifier], [task taskIdentifier]];

/ios/Classes/FlutterDownloaderPlugin.m:373:15: 'stringByReplacingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByRemovingPercentEncoding instead, which always uses the recommended UTF-8 encoding. [-Wdeprecated-declarations]
     ? [origin stringByReplacingPercentEscapesUsingEncoding:NSUTF8StringEncoding]

/ios/Classes/FlutterDownloaderPlugin.m:373:15: 'stringByReplacingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByRemovingPercentEncoding instead, which always uses the recommended UTF-8 encoding. [-Wdeprecated-declarations]
     ? [origin stringByReplacingPercentEscapesUsingEncoding:NSUTF8StringEncoding]
```

**Comment by Faiz-rhm** [comment] 2021-08-08 06:49
any solutions yet?

**Comment by bartekpacia** [comment] 2022-05-23 13:02
I can't reproduce this. Closing. Probably it's been fixed.

Feel free to comment/reopen once you have a reproducible sample.

**Closed by bartekpacia** 2022-05-23 13:02 UTC
