### ISSUE TITLE
Outdated API?

### ISSUE THREAD

**Issue by stylehuan** [fluttercommunity/flutter_downloader#99] opened 2019-08-13 02:26 UTC
![image](https://user-images.githubusercontent.com/6212099/62910857-c6e26700-bdb4-11e9-83fd-c3d697cbfad8.png)

注: /Users/stylehuan/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_downloader-1.1.9/android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

**Comment by hnvn** [comment] 2019-08-13 03:40
This issue will be resolved in next release, if you can't wait for it, you can try to config your pubspec with github url

**Closed by hnvn** 2019-08-13 03:40 UTC

**Comment by hnvn** [comment] 2019-08-14 03:01
Duplicate of #89
