### ISSUE TITLE
The Application must be implemented PluginRegistrantCallback 

### ISSUE THREAD

**Issue by johnny-stevie** [fluttercommunity/flutter_downloader#171] opened 2019-11-10 21:49 UTC
I get this error when I download the latest version of flutter_downloader
Android Manifest.xml
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.johnwall.quick_song"> 

    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    
    <application
        tools:replace="android:label"

        android:name="io.flutter.app.FlutterApplication"
        android:label="quick_song"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
        <provider
            android:name="androidx.work.impl.WorkManagerInitializer"
            android:authorities="${applicationId}.workmanager-init"
            android:enabled="false"
            android:exported="false" />

        <provider
            android:name="vn.hunghd.flutterdownloader.FlutterDownloaderInitializer"
            android:authorities="${applicationId}.flutter-downloader-init"
            android:exported="false">
            <meta-data
                android:name="vn.hunghd.flutterdownloader.MAX_CONCURRENT_TASKS"
                android:value="5" /> 
        </provider>
    </application>
</manifest>
`
Error
`E/AndroidRuntime(17932): java.lang.AssertionError: The Application must be implemented PluginRegistrantCallback
E/AndroidRuntime(17932):        at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:106)
E/AndroidRuntime(17932):        at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
E/AndroidRuntime(17932):        at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)`

Any help?

**Comment by hnvn** [comment] 2019-11-11 02:02
Duplicate of #166, #152, #141. Why do people keep reporting this matter? Instead, you just need to read changelogs, document and check closed issues and get the solution quickly.

**Closed by hnvn** 2019-11-11 02:02 UTC

**Comment by johnny-stevie** [comment] 2019-11-11 18:51
I've looked at your example code, the issues, the documents and nothing has offered any solution to my problem. I think that your example code isnt clear on how to implement the java code in Android Manifest.xml 
If I follow the example xml, the app doesnt start as i set 
`android:name=".MyApplication" `
but if i set
`android:name="io.plugin.FlutterApplication"`
it does start but without PluginRegistrantCallback being implemented.
What is the proper way of doing it?
Any help is appreciated, thank you for your response.

**Comment by LLemonGreen** [comment] 2019-11-19 14:11
@johnny-stevie same issue

**Comment by hnvn** [comment] 2019-11-19 15:23
Do you read this [instruction](https://github.com/fluttercommunity/flutter_downloader#required-configuration-1)?

**Comment by LLemonGreen** [comment] 2019-11-19 15:43
> Do you read this [instruction](https://github.com/fluttercommunity/flutter_downloader#required-configuration-1)?

sorry i forgot an import in  MyApplication.kt
 
 `import io.flutter.plugins.GeneratedPluginRegistrant;
`
my fault

**Comment by Rajesh-Konki** [comment] 2020-01-02 11:20
what about the file GeneratedPluginRegistrant.java which defaultly creates?
