### ISSUE TITLE
[Feature request] Add Cancel and Pause / Resume buttons to notification

### ISSUE THREAD

**Issue by SerpentDash** [fluttercommunity/flutter_downloader#610] opened 2022-02-28 12:08 UTC
This could be really useful feature to let end user cancel or pause downloading from notifications, especially if we don't make any other way to cancel task (eg if our app doesn't have any cancel button).

Implementation should be pretty straight forward, in Notification builder (DownloadWorker.java) add two actions, create two PendingIntents for corresponding functionalities and remove those buttons when DownloadStatus is 'Complete'.

**Comment by Ev1lT3rm1nal** [comment] 2022-03-01 21:45
You can do your own notification and handle it with the callbacks, or you can handle the click on the notification to get you into a screen where you can cancel, pause, etc.

**Comment by SerpentDash** [comment] 2022-03-06 20:54
Of course I can... All devs that are using this plugin can... But why we should be using yet another plugin for notification handling if this plugin already has it? Why reinvent wheel if we already have a fully functioning car?
All I'm asking is small improvement to notification. Shouldn't be a big of a deal to implement this for someone who is familiar with source code (i guess?). Devs and end users should appreciate ability to cancel / pause current task from background using just one click on notification.

**Comment by dragongesa** [comment] 2022-03-30 02:40
really need it. any update?

**Comment by bartekpacia** [comment] 2022-05-23 15:44
duplicate of #28

**Closed by bartekpacia** 2022-05-23 15:44 UTC
Labels: good first issue, feature request
