### ISSUE TITLE
The Application must be implemented PluginRegistrantCallback

### ISSUE THREAD

**Issue by StarSkyK** [fluttercommunity/flutter_downloader#152] opened 2019-10-29 08:24 UTC
Android 
flutter_downloader: ^1.3.2

this is  download code 
android app will crash when i clicked button 

```dart
void downLoadFile() async {
    String path = await SMTool.getDownloadPath(context);
    tkID = await FlutterDownloader.enqueue(
    url:"http://okxxxxzy.xzokzyzy.com/20190927/23826_b55e98a7/%e8%88%92%e5%85%8b%e8%b4%9d%e5%a1%94%e7%ac%ac01%e8%af%9d.mp4",
      savedDir: path,
      showNotification: true,
      fileName: 'video3.mp4',
      openFileFromNotification: true,
    );
  }
```
this is exception message
```
E/AndroidRuntime(15448): FATAL EXCEPTION: main
E/AndroidRuntime(15448): Process: com.example.show_me_tv, PID: 15448
E/AndroidRuntime(15448): java.lang.AssertionError: The Application must be implemented PluginRegistrantCallback
E/AndroidRuntime(15448): 	at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:106)
E/AndroidRuntime(15448): 	at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
E/AndroidRuntime(15448): 	at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
E/AndroidRuntime(15448): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(15448): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(15448): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(15448): 	at android.app.ActivityThread.main(ActivityThread.java:5563)
E/AndroidRuntime(15448): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15448): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
E/AndroidRuntime(15448): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
I/Process (15448): Sending signal. PID: 15448 SIG: 9
Lost connection to device.
```
i checked the config
this is the config
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.show_me_tv">

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <uses-permission android:name ="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name ="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name ="android.permission.WRITE_EXTERNAL_STORAGE" />

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="ShowMeTv"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
    </application>
</manifest>
```
this is mainactivity.kt
```
package com.example.show_me_tv

import android.content.BroadcastReceiver
import android.content.ComponentCallbacks
import android.content.Intent
import android.content.IntentFilter
import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.plugin.common.PluginRegistry;
import vn.hunghd.flutterdownloader.FlutterDownloaderPlugin

class MainActivity: FlutterActivity(),PluginRegistry.PluginRegistrantCallback {
    override fun registerWith(p0: PluginRegistry?) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
        GeneratedPluginRegistrant.registerWith(p0);
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(this)
    }

}

```
i need help ,please

**Comment by StarSkyK** [comment] 2019-10-29 08:29
@hnvn please

**Comment by nidhinpuliyannoor** [comment] 2019-10-29 08:36
Please help.iam having the same issue
 FATAL EXCEPTION: main
E/AndroidRuntime(22985): Process: com.example.videoplayer, PID: 22985
E/AndroidRuntime(22985): java.lang.AssertionError: The Application must be implemented PluginRegistrantCallback

**Comment by hnvn** [comment] 2019-10-29 08:38
Duplicate of #141

**Comment by StarSkyK** [comment] 2019-10-29 08:38
> Please help. I am having the same issue
> FATAL EXCEPTION: main
> E/AndroidRuntime(22985): Process: com.example.videoplayer, PID: 22985
> E/AndroidRuntime(22985): java.lang.AssertionError: The Application must be implemented PluginRegistrantCallback
metoo , but i  implemented PluginRegistrantCallback

**Closed by hnvn** 2019-10-29 08:38 UTC

**Comment by StarSkyK** [comment] 2019-10-29 08:41
> Duplicate of #141

no , i have read it ,but it doesn't work

**Comment by hnvn** [comment] 2019-10-29 08:43
I see you follow the wrong configuration in #141 , not the solution. Check it again
