### ISSUE TITLE
failed to set registerPlugins on iOS

### ISSUE THREAD

**Issue by erperejildo** [fluttercommunity/flutter_downloader#464] opened 2021-05-01 22:03 UTC
```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'failed to set registerPlugins'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20422fba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20193ff5 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20422de3 +[NSException raise:format:] + 0
	3   Foundation                          0x00007fff207748e7 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   flutter_downloader                  0x00000001104732d0 -[FlutterDownloaderPlugin startBackgroundIsolate:] + 528
	5   flutter_downloader                  0x0000000110478f99 -[FlutterDownloaderPlugin initializeMethodCall:result:] + 297
	6   flutter_downloader                  0x000000011047cc9f -[FlutterDownloaderPlugin handleMethodCall:result:] + 191
	7   Flutter                             0x0000000112636fca __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	8   Flutter                             0x0000000111def1fa _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
	9   Flutter                             0x0000000111df440a _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 38
	10  Flutter                             0x0000000112181ab9 _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_36NS_9allocatorIS8_EEFvvEEclEv + 83
	11  Flutter                             0x000000011210569a _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 160
	12  Flutter                             0x000000011210a0e6 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	13  CoreFoundation                      0x00007fff2039178a __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	14  CoreFoundation                      0x00007fff2039127c __CFRunLoopDoTimer + 924
	15  CoreFoundation                      0x00007fff2039081a __CFRunLoopDoTimers + 265
	16  CoreFoundation                      0x00007fff2038ae69 __CFRunLoopRun + 2013
	17  CoreFoundation                      0x00007fff2038a1a7 CFRunLoopRunSpecific + 567
	18  GraphicsServices                    0x00007fff2b874d85 GSEventRunModal + 139
	19  UIKitCore                           0x00007fff246c14df -[UIApplication _run] + 912
	20  UIKitCore                           0x00007fff246c639c UIApplicationMain + 101
	21  Runner                              0x000000010cc7579b main + 75
	22  libdyld.dylib                       0x00007fff2025abbd start + 1
)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'failed to set registerPlugins'
terminating with uncaught exception of type NSException
CoreSimulator 757.5 - Device: iPhone 8 (725A6C0C-3CFE-48F4-8321-94422034BA04) - Runtime: iOS 14.5 (18E182) - DeviceType: iPhone 8
(lldb) 
```

**Comment by dan19-82** [comment] 2021-05-12 15:20
I had this but you have to follow the setup in xcode for iOS.
Follow the first answer on this 
https://stackoverflow.com/questions/66181736/flutterdownloader-works-downloading-pdf-in-android-but-fails-on-ios

**Comment by erperejildo** [comment] 2021-05-13 08:55
it worked after changing some iOS files manually. Before that it was throwing some other issues related to the initialisation

**Comment by bartekpacia** [comment] 2022-05-24 11:25
Without a sample repo demonstrating the problem I'll have to close this because it's nonreproducible.

Also from the comments, it seems like the cause is incorrect setup.

**Closed by bartekpacia** 2022-05-24 11:25 UTC
